"""Update Topic model.

Revision ID: 1e0e194f4e83
Revises: 127e269e6a68
Create Date: 2015-06-10 20:33:04.360664

"""

# revision identifiers, used by Alembic.
revision = '1e0e194f4e83'
down_revision = '127e269e6a68'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'desc')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('desc', mysql.TEXT(), nullable=True))
    ### end Alembic commands ###
