"""Add score to RelevantTopic model.

Revision ID: 9ada972beb4
Revises: 54d537392f44
Create Date: 2015-07-13 22:35:13.561894

"""

# revision identifiers, used by Alembic.
revision = '9ada972beb4'
down_revision = '54d537392f44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relevant_topic', sa.Column('score', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relevant_topic', 'score')
    ### end Alembic commands ###
