"""Add UserUpvoteStatistics model.

Revision ID: 5532ac2b35c2
Revises: 227323b68291
Create Date: 2015-06-13 16:36:23.837677

"""

# revision identifiers, used by Alembic.
revision = '5532ac2b35c2'
down_revision = '227323b68291'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_upvote_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upvotes_count', sa.Integer(), nullable=True),
    sa.Column('upvoter_followings_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('upvoter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upvoter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_upvote_statistics')
    ### end Alembic commands ###
