"""Update UserTopicStatistic model.

Revision ID: 6d1950977cb
Revises: 37c44549441
Create Date: 2015-06-14 20:00:16.891685

"""

# revision identifiers, used by Alembic.
revision = '6d1950977cb'
down_revision = '37c44549441'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_topic_statistic', sa.Column('week_answers_count', sa.String(length=200), nullable=True))
    op.add_column('user_topic_statistic', sa.Column('week_score', sa.Float(), nullable=True))
    op.add_column('user_topic_statistic', sa.Column('week_upvotes_count', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_topic_statistic', 'week_upvotes_count')
    op.drop_column('user_topic_statistic', 'week_score')
    op.drop_column('user_topic_statistic', 'week_answers_count')
    ### end Alembic commands ###
