"""Add QuestionEditLog.

Revision ID: 1265feed2b01
Revises: 17092c6c1158
Create Date: 2015-05-29 10:04:25.923747

"""

# revision identifiers, used by Alembic.
revision = '1265feed2b01'
down_revision = '17092c6c1158'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('before', sa.String(length=200), nullable=True),
    sa.Column('before_id', sa.Integer(), nullable=True),
    sa.Column('after', sa.String(length=200), nullable=True),
    sa.Column('after_id', sa.Integer(), nullable=True),
    sa.Column('compare', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_edit_log')
    ### end Alembic commands ###
