"""Add is_active to User.

Revision ID: 255b67e4516b
Revises: 52c787783795
Create Date: 2015-05-30 17:00:54.226256

"""

# revision identifiers, used by Alembic.
revision = '255b67e4516b'
down_revision = '52c787783795'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    ### end Alembic commands ###
