"""Add avatar to Topic

Revision ID: 3c77900d8141
Revises: 1b8614377bc0
Create Date: 2015-05-27 10:50:32.633491

"""

# revision identifiers, used by Alembic.
revision = '3c77900d8141'
down_revision = '1b8614377bc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('avatar', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'avatar')
    ### end Alembic commands ###
