"""Add merged to Notification model.

Revision ID: 1832b1926d63
Revises: 23ca6f919368
Create Date: 2015-07-25 23:53:12.492269

"""

# revision identifiers, used by Alembic.
revision = '1832b1926d63'
down_revision = '23ca6f919368'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('merged', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'merged')
    ### end Alembic commands ###
