"""Update QuestionEditLog.

Revision ID: 24037549524a
Revises: 30724444845d
Create Date: 2015-05-29 10:26:49.271007

"""

# revision identifiers, used by Alembic.
revision = '24037549524a'
down_revision = '30724444845d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_edit_log', 'kind', type_=sa.String(50), existing_type=sa.Integer())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
