"""Update User model.

Revision ID: 2a027906937c
Revises: 2f0ab9eb095f
Create Date: 2015-06-23 16:49:06.082264

"""

# revision identifiers, used by Alembic.
revision = '2a027906937c'
down_revision = '2f0ab9eb095f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('drafts_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'drafts_count')
    ### end Alembic commands ###
