"""Add topic_id to HomeFeedBackup.

Revision ID: 829d75e594e
Revises: 1334692cc30e
Create Date: 2015-07-15 12:00:09.747708

"""

# revision identifiers, used by Alembic.
revision = '829d75e594e'
down_revision = '1334692cc30e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_feed_backup', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'home_feed_backup', 'topic', ['topic_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'home_feed_backup', type_='foreignkey')
    op.drop_column('home_feed_backup', 'topic_id')
    ### end Alembic commands ###
