"""Add ApplyTopicDeletion model.

Revision ID: 1a0298aecde9
Revises: 902805df097
Create Date: 2015-06-21 11:06:24.773811

"""

# revision identifiers, used by Alembic.
revision = '1a0298aecde9'
down_revision = '902805df097'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply_topic_deletion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apply_topic_deletion')
    ### end Alembic commands ###
