"""Update Notification model.

Revision ID: e2a6a5bbd5a
Revises: 1ef8556a1aa2
Create Date: 2015-06-28 21:03:35.012090

"""

# revision identifiers, used by Alembic.
revision = 'e2a6a5bbd5a'
down_revision = '1ef8556a1aa2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('senders_list', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'senders_list')
    ### end Alembic commands ###
