"""Update Question

Revision ID: 349dd29dc
Revises: 4ecec2f9c787
Create Date: 2015-05-26 08:23:51.700844

"""

# revision identifiers, used by Alembic.
revision = '349dd29dc'
down_revision = '4ecec2f9c787'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('desc', sa.Text(), nullable=True))
    op.drop_column('question', 'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_column('question', 'desc')
    ### end Alembic commands ###
