"""Update User & UserTopicStatistics models.

Revision ID: 1d0108e5c937
Revises: 1d515b36e647
Create Date: 2015-05-31 11:13:47.317959

"""

# revision identifiers, used by Alembic.
revision = '1d0108e5c937'
down_revision = '1d515b36e647'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_expert_topic')
    op.add_column('user', sa.Column('has_seleted_expert_topics', sa.Boolean(), nullable=True))
    op.drop_column('user', 'has_edited_expert_topics')
    op.add_column('user_topic_statistics', sa.Column('selected', sa.Boolean(), nullable=True))
    op.add_column('user_topic_statistics', sa.Column('show_order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_topic_statistics', 'show_order')
    op.drop_column('user_topic_statistics', 'selected')
    op.add_column('user', sa.Column('has_edited_expert_topics', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'has_seleted_expert_topics')
    op.create_table('user_expert_topic',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('show_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('topic_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], [u'topic.id'], name=u'user_expert_topic_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'user_expert_topic_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
