"""Add has_edited_expert_topics to User model.

Revision ID: 1d515b36e647
Revises: 364356c6b147
Create Date: 2015-05-31 11:03:27.620607

"""

# revision identifiers, used by Alembic.
revision = '1d515b36e647'
down_revision = '364356c6b147'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_edited_expert_topics', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_edited_expert_topics')
    ### end Alembic commands ###
