"""Add path_length to TopicClosure table.

Revision ID: 45054882c141
Revises: 35ff8c684ce1
Create Date: 2015-05-25 16:54:44.803060

"""

# revision identifiers, used by Alembic.
revision = '45054882c141'
down_revision = '35ff8c684ce1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_closure', sa.Column('path_length', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_closure', 'path_length')
    ### end Alembic commands ###
