"""Add comments_count & followers_count to Question.

Revision ID: 52c787783795
Revises: 36d6b61d3bce
Create Date: 2015-05-30 15:45:57.710545

"""

# revision identifiers, used by Alembic.
revision = '52c787783795'
down_revision = '36d6b61d3bce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('followers_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'followers_count')
    op.drop_column('question', 'comments_count')
    ### end Alembic commands ###
