"""Rm title from answer.

Revision ID: 17092c6c1158
Revises: 286864df452b
Create Date: 2015-05-28 20:52:49.010210

"""

# revision identifiers, used by Alembic.
revision = '17092c6c1158'
down_revision = '286864df452b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'title')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('title', mysql.VARCHAR(length=100), nullable=True))
    ### end Alembic commands ###
