"""Add worked_on to UserTopicStatistic.

Revision ID: 4eac334fcf8e
Revises: 4257d0a1f1d4
Create Date: 2015-07-09 09:44:31.338259

"""

# revision identifiers, used by Alembic.
revision = '4eac334fcf8e'
down_revision = '4257d0a1f1d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_topic_statistic', sa.Column('worked_on', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_topic_statistic', 'worked_on')
    ### end Alembic commands ###
