"""Add identity to Answer model.

Revision ID: 465d0bcc0b83
Revises: 52bbf8d2c270
Create Date: 2015-06-15 11:09:14.688685

"""

# revision identifiers, used by Alembic.
revision = '465d0bcc0b83'
down_revision = '52bbf8d2c270'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('identity', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'identity')
    ### end Alembic commands ###
