"""Add has_selected_interesting_topics to User mode.

Revision ID: 57cefece6e6d
Revises: 278b7e4bcf01
Create Date: 2015-07-08 10:04:03.867118

"""

# revision identifiers, used by Alembic.
revision = '57cefece6e6d'
down_revision = '278b7e4bcf01'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_selected_expert_topics', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('has_selected_interesting_topics', sa.Boolean(), nullable=True))
    op.drop_column('user', 'has_seleted_expert_topics')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_seleted_expert_topics', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user', 'has_selected_interesting_topics')
    op.drop_column('user', 'has_selected_expert_topics')
    ### end Alembic commands ###
