"""Update topic model.

Revision ID: 577f842b8215
Revises: 4ab8a4f268cf
Create Date: 2015-07-10 17:25:32.634375

"""

# revision identifiers, used by Alembic.
revision = '577f842b8215'
down_revision = '4ab8a4f268cf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('kind', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('merge_topic_locked', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('other_kind', sa.String(length=100), nullable=True))
    op.add_column('topic', sa.Column('topic_kind_locked', sa.Boolean(), nullable=True))
    op.drop_column('topic', 'desc_locked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('desc_locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('topic', 'topic_kind_locked')
    op.drop_column('topic', 'other_kind')
    op.drop_column('topic', 'merge_topic_locked')
    op.drop_column('topic', 'kind')
    ### end Alembic commands ###
