"""Update Answer model.

Revision ID: 364356c6b147
Revises: 255b67e4516b
Create Date: 2015-05-31 09:31:14.707070

"""

# revision identifiers, used by Alembic.
revision = '364356c6b147'
down_revision = '255b67e4516b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('hide', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'hide')
    ### end Alembic commands ###
