"""Update User model.

Revision ID: 278b7e4bcf01
Revises: 5791f7adaa15
Create Date: 2015-06-30 11:27:19.479017

"""

# revision identifiers, used by Alembic.
revision = '278b7e4bcf01'
down_revision = '5791f7adaa15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_read_message_notifications_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_read_thanks_notifications_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_read_user_notifications_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_read_user_notifications_at')
    op.drop_column('user', 'last_read_thanks_notifications_at')
    op.drop_column('user', 'last_read_message_notifications_at')
    ### end Alembic commands ###
