"""Add unread to ComposeFeed.

Revision ID: 3ef23c7621bd
Revises: 9ada972beb4
Create Date: 2015-07-14 17:51:12.094253

"""

# revision identifiers, used by Alembic.
revision = '3ef23c7621bd'
down_revision = '9ada972beb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compose_feed', sa.Column('unread', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compose_feed', 'unread')
    ### end Alembic commands ###
