"""Update QuestionEditLog.

Revision ID: 30724444845d
Revises: 1265feed2b01
Create Date: 2015-05-29 10:15:38.772391

"""

# revision identifiers, used by Alembic.
revision = '30724444845d'
down_revision = '1265feed2b01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_edit_log', sa.Column('original_desc', sa.Text(), nullable=True))
    op.add_column('question_edit_log', sa.Column('original_title', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_edit_log', 'original_title')
    op.drop_column('question_edit_log', 'original_desc')
    ### end Alembic commands ###
