"""Add from_merge to QuestionTopic model.

Revision ID: 1a5c49be1d1a
Revises: 23196ac7e33d
Create Date: 2015-07-13 11:26:19.715249

"""

# revision identifiers, used by Alembic.
revision = '1a5c49be1d1a'
down_revision = '23196ac7e33d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_topic', sa.Column('from_merge', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_topic', 'from_merge')
    ### end Alembic commands ###
