"""Add topic expert model.

Revision ID: 1b3d9d54b97e
Revises: 29b348ba806d
Create Date: 2015-05-29 23:03:43.360145

"""

# revision identifiers, used by Alembic.
revision = '1b3d9d54b97e'
down_revision = '29b348ba806d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_expert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upvotes_count', sa.Integer(), nullable=True),
    sa.Column('answers_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_expert')
    ### end Alembic commands ###
