"""Add current to WorkOnProduct model.

Revision ID: 4257d0a1f1d4
Revises: 5954975a456a
Create Date: 2015-07-08 16:40:12.855233

"""

# revision identifiers, used by Alembic.
revision = '4257d0a1f1d4'
down_revision = '5954975a456a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_on_product', sa.Column('current', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_on_product', 'current')
    ### end Alembic commands ###
