"""Add topic_experience to answer.

Revision ID: 26a4ef30de7e
Revises: 1b2374eb5e99
Create Date: 2015-06-03 22:21:42.686047

"""

# revision identifiers, used by Alembic.
revision = '26a4ef30de7e'
down_revision = '1b2374eb5e99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('topic_experience', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'topic_experience')
    ### end Alembic commands ###
