"""Add shares_count to Answer model.

Revision ID: 4e4b09398ef6
Revises: 26a4ef30de7e
Create Date: 2015-06-07 08:37:57.621615

"""

# revision identifiers, used by Alembic.
revision = '4e4b09398ef6'
down_revision = '26a4ef30de7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('shares_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'shares_count')
    ### end Alembic commands ###
