"""Update answer & question models.

Revision ID: c6828270310
Revises: 829d75e594e
Create Date: 2015-07-15 15:14:33.815950

"""

# revision identifiers, used by Alembic.
revision = 'c6828270310'
down_revision = '829d75e594e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('fantastic', sa.Boolean(), nullable=True))
    op.add_column('question', sa.Column('hot', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'hot')
    op.drop_column('answer', 'fantastic')
    ### end Alembic commands ###
