"""Add qrcode to Answer model.

Revision ID: 23ca6f919368
Revises: 42eacc1e5733
Create Date: 2015-07-21 11:28:57.776925

"""

# revision identifiers, used by Alembic.
revision = '23ca6f919368'
down_revision = '42eacc1e5733'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('qrcode', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'qrcode')
    ### end Alembic commands ###
