"""Add answered to ComposeFeed & InivteAnswer models.

Revision ID: 575337dd3238
Revises: e010cbee6b1
Create Date: 2015-07-11 12:16:33.130056

"""

# revision identifiers, used by Alembic.
revision = '575337dd3238'
down_revision = 'e010cbee6b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compose_feed', sa.Column('answered', sa.Boolean(), nullable=True))
    op.add_column('invite_answer', sa.Column('answered', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_answer', 'answered')
    op.drop_column('compose_feed', 'answered')
    ### end Alembic commands ###
