"""Add comment_id to LikeAnswerComment.

Revision ID: 31d6b3bc5900
Revises: 3f052d6318f9
Create Date: 2015-06-02 14:27:35.304333

"""

# revision identifiers, used by Alembic.
revision = '31d6b3bc5900'
down_revision = '3f052d6318f9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like_answer_comment', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'like_answer_comment_ibfk_1', 'like_answer_comment', type_='foreignkey')
    op.create_foreign_key(None, 'like_answer_comment', 'answer_comment', ['comment_id'], ['id'])
    op.drop_column('like_answer_comment', 'answer_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like_answer_comment', sa.Column('answer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'like_answer_comment', type_='foreignkey')
    op.create_foreign_key(u'like_answer_comment_ibfk_1', 'like_answer_comment', 'answer', ['answer_id'], ['id'])
    op.drop_column('like_answer_comment', 'comment_id')
    ### end Alembic commands ###
