"""Update topic model.

Revision ID: e010cbee6b1
Revises: 577f842b8215
Create Date: 2015-07-10 17:48:12.231444

"""

# revision identifiers, used by Alembic.
revision = 'e010cbee6b1'
down_revision = '577f842b8215'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('all_locked', sa.Boolean(), nullable=True))
    op.drop_column('topic', 'locked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('topic', 'all_locked')
    ### end Alembic commands ###
