"""Rename QuestionEditLog to PublicEditLog

Revision ID: 29b348ba806d
Revises: 24037549524a
Create Date: 2015-05-29 18:33:49.774564

"""

# revision identifiers, used by Alembic.
revision = '29b348ba806d'
down_revision = '24037549524a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('before', sa.String(length=200), nullable=True),
    sa.Column('before_id', sa.Integer(), nullable=True),
    sa.Column('after', sa.String(length=200), nullable=True),
    sa.Column('after_id', sa.Integer(), nullable=True),
    sa.Column('compare', sa.String(length=500), nullable=True),
    sa.Column('original_title', sa.String(length=200), nullable=True),
    sa.Column('original_desc', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question_edit_log')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_edit_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('kind', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('before', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('before_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('after', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('after_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('compare', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('original_desc', mysql.TEXT(), nullable=True),
    sa.Column('original_title', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], [u'question.id'], name=u'question_edit_log_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'question_edit_log_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('public_edit_log')
    ### end Alembic commands ###
