"""Add original_name to PublicEditLog.

Revision ID: 4be4542b23e9
Revises: 4b214414c2ec
Create Date: 2015-05-31 19:45:36.390133

"""

# revision identifiers, used by Alembic.
revision = '4be4542b23e9'
down_revision = '4b214414c2ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_edit_log', sa.Column('original_name', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_edit_log', 'original_name')
    ### end Alembic commands ###
