"""Add answer_comment_id to Notification model.

Revision ID: 1b2374eb5e99
Revises: 31d6b3bc5900
Create Date: 2015-06-02 22:35:15.457412

"""

# revision identifiers, used by Alembic.
revision = '1b2374eb5e99'
down_revision = '31d6b3bc5900'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('answer_comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'answer_comment', ['answer_comment_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'answer_comment_id')
    ### end Alembic commands ###
