"""Add merge_to_topic_id to Topic model.

Revision ID: 23196ac7e33d
Revises: 575337dd3238
Create Date: 2015-07-13 10:56:42.470381

"""

# revision identifiers, used by Alembic.
revision = '23196ac7e33d'
down_revision = '575337dd3238'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('merge_to_topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic', 'topic', ['merge_to_topic_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_column('topic', 'merge_to_topic_id')
    ### end Alembic commands ###
