"""Update user model

Revision ID: 227323b68291
Revises: 3e4cd5c1f8bf
Create Date: 2015-06-12 23:55:47.934832

"""

# revision identifiers, used by Alembic.
revision = '227323b68291'
down_revision = '3e4cd5c1f8bf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('location', sa.String(length=100), nullable=True))
    op.drop_column('user', 'city')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'location')
    ### end Alembic commands ###
