"""Update AnswerComment model.

Revision ID: 3606d4a47663
Revises: 2040a458fc8a
Create Date: 2015-06-24 09:06:37.957787

"""

# revision identifiers, used by Alembic.
revision = '3606d4a47663'
down_revision = '2040a458fc8a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_comment', sa.Column('likes_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_comment', 'likes_count')
    ### end Alembic commands ###
