"""Update Answer model.

Revision ID: 1d61f5c015c
Revises: 3cf652d92bfc
Create Date: 2015-06-10 10:13:49.804629

"""

# revision identifiers, used by Alembic.
revision = '1d61f5c015c'
down_revision = '3cf652d92bfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('content_length', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('content_preview', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'content_preview')
    op.drop_column('answer', 'content_length')
    ### end Alembic commands ###
