"""Add unread to User model.

Revision ID: 1ef8556a1aa2
Revises: 3f2c86e3bf8b
Create Date: 2015-06-28 20:59:07.515363

"""

# revision identifiers, used by Alembic.
revision = '1ef8556a1aa2'
down_revision = '3f2c86e3bf8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('created_at_date', sa.Date(), nullable=True))
    op.add_column('notification', sa.Column('unread', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'unread')
    op.drop_column('notification', 'created_at_date')
    ### end Alembic commands ###
