"""Add user_id to question.

Revision ID: 1b8614377bc0
Revises: 349dd29dc
Create Date: 2015-05-26 11:16:49.128605

"""

# revision identifiers, used by Alembic.
revision = '1b8614377bc0'
down_revision = '349dd29dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'user_id')
    ### end Alembic commands ###
