"""Rename table user_upvotes_statistics.

Revision ID: 381acdce0a35
Revises: 3e72085bf89b
Create Date: 2015-06-13 17:01:31.859738

"""

# revision identifiers, used by Alembic.
revision = '381acdce0a35'
down_revision = '3e72085bf89b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_upvote_statistics', 'user_upvote_statistic')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_upvote_statistic', 'user_upvote_statistics')
    ### end Alembic commands ###
