"""Update User model.

Revision ID: 198b92dbe210
Revises: 5a66f56497fc
Create Date: 2015-06-22 09:09:33.926392

"""

# revision identifiers, used by Alembic.
revision = '198b92dbe210'
down_revision = '5a66f56497fc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name_edit_count', sa.Integer(), nullable=True))
    op.drop_column('user', 'name_modify_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name_modify_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'name_edit_count')
    ### end Alembic commands ###
