"""Add hide_from_hot to Topic.

Revision ID: 15f3d22cf56e
Revises: c8b29188c6d
Create Date: 2015-07-15 18:11:19.658443

"""

# revision identifiers, used by Alembic.
revision = '15f3d22cf56e'
down_revision = 'c8b29188c6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('hide_from_hot', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'hide_from_hot')
    ### end Alembic commands ###
