"""Add from_merge to FollowTopic & TopicClosure.

Revision ID: 36324d0081c5
Revises: 1a5c49be1d1a
Create Date: 2015-07-13 12:38:20.199404

"""

# revision identifiers, used by Alembic.
revision = '36324d0081c5'
down_revision = '1a5c49be1d1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_topic', sa.Column('from_merge', sa.Boolean(), nullable=True))
    op.add_column('topic_closure', sa.Column('from_merge', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_closure', 'from_merge')
    op.drop_column('follow_topic', 'from_merge')
    ### end Alembic commands ###
