"""Add followers_count to Topic.

Revision ID: 2a0d468e36e7
Revises: 465d0bcc0b83
Create Date: 2015-06-19 00:04:22.481847

"""

# revision identifiers, used by Alembic.
revision = '2a0d468e36e7'
down_revision = '465d0bcc0b83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('followers_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'followers_count')
    ### end Alembic commands ###
