"""Add from_merge to TopicSynonym.

Revision ID: 5a8acd5e973d
Revises: 36324d0081c5
Create Date: 2015-07-13 13:22:54.605324

"""

# revision identifiers, used by Alembic.
revision = '5a8acd5e973d'
down_revision = '36324d0081c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_synonym', sa.Column('from_merge', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_synonym', 'from_merge')
    ### end Alembic commands ###
