"""Add 

Revision ID: 54d537392f44
Revises: 5a8acd5e973d
Create Date: 2015-07-13 22:27:25.440674

"""

# revision identifiers, used by Alembic.
revision = '54d537392f44'
down_revision = '5a8acd5e973d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relevant_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('relevant_topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relevant_topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'topic', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='unique')
    op.drop_table('relevant_topic')
    ### end Alembic commands ###
