"""Add anonymous to Answer model.

Revision ID: 52bbf8d2c270
Revises: 5a84759e26b6
Create Date: 2015-06-15 10:39:50.271421

"""

# revision identifiers, used by Alembic.
revision = '52bbf8d2c270'
down_revision = '5a84759e26b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('anonymous', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'anonymous')
    ### end Alembic commands ###
