"""Add score to Answer model.

Revision ID: 4b214414c2ec
Revises: 1d0108e5c937
Create Date: 2015-05-31 16:45:52.370836

"""

# revision identifiers, used by Alembic.
revision = '4b214414c2ec'
down_revision = '1d0108e5c937'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('score', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'score')
    ### end Alembic commands ###
