"""Update User model.

Revision ID: 76552dc6a2f
Revises: 198b92dbe210
Create Date: 2015-06-22 10:12:40.905798

"""

# revision identifiers, used by Alembic.
revision = '76552dc6a2f'
down_revision = '198b92dbe210'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('inactive_email', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'inactive_email')
    ### end Alembic commands ###
