"""Update ComposeFeed model.

Revision ID: 5a84759e26b6
Revises: 6d1950977cb
Create Date: 2015-06-14 23:45:12.698175

"""

# revision identifiers, used by Alembic.
revision = '5a84759e26b6'
down_revision = '6d1950977cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compose_feed', sa.Column('invitation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'compose_feed', 'invite_answer', ['invitation_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compose_feed', type_='foreignkey')
    op.drop_column('compose_feed', 'invitation_id')
    ### end Alembic commands ###
