"""Update Topic models.

Revision ID: c8b29188c6d
Revises: c6828270310
Create Date: 2015-07-15 16:18:27.087031

"""

# revision identifiers, used by Alembic.
revision = 'c8b29188c6d'
down_revision = 'c6828270310'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('avg', sa.Float(), nullable=True))
    op.add_column('topic', sa.Column('hot_score', sa.Float(), nullable=True))
    op.add_column('topic', sa.Column('sqrt_avg', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'sqrt_avg')
    op.drop_column('topic', 'hot_score')
    op.drop_column('topic', 'avg')
    ### end Alembic commands ###
