"""Add name_pinyin to User mode.

Revision ID: 2a1cf8938dea
Revises: be77483e65b
Create Date: 2015-06-01 15:46:55.908685

"""

# revision identifiers, used by Alembic.
revision = '2a1cf8938dea'
down_revision = 'be77483e65b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name_pinyin', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name_pinyin')
    ### end Alembic commands ###
