"""Add InvitationCode and update User

Revision ID: 2c46d478067d
Revises: e1b05a198a8
Create Date: 2015-05-25 17:35:32.396996

"""

# revision identifiers, used by Alembic.
revision = '2c46d478067d'
down_revision = 'e1b05a198a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('sended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('answers_count', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('desc', sa.String(length=200), nullable=True))
    op.add_column(u'user', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('followings_count', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('questions_count', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('thanks_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'thanks_count')
    op.drop_column(u'user', 'questions_count')
    op.drop_column(u'user', 'followings_count')
    op.drop_column(u'user', 'followers_count')
    op.drop_column(u'user', 'desc')
    op.drop_column(u'user', 'answers_count')
    op.drop_table('invitation_code')
    ### end Alembic commands ###
