"""Add ignore to InviteAnswer model.

Revision ID: 2040a458fc8a
Revises: 2a027906937c
Create Date: 2015-06-23 23:41:22.550034

"""

# revision identifiers, used by Alembic.
revision = '2040a458fc8a'
down_revision = '2a027906937c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_answer', sa.Column('ignore', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_answer', 'ignore')
    ### end Alembic commands ###
