"""Update Answer model.

Revision ID: 127e269e6a68
Revises: 30bc9e463992
Create Date: 2015-06-10 17:26:40.838540

"""

# revision identifiers, used by Alembic.
revision = '127e269e6a68'
down_revision = '30bc9e463992'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('content_preview_truncated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'content_preview_truncated')
    ### end Alembic commands ###
