"""Add last_read_compose_feeds_at to User.

Revision ID: 1c8be8d9bec3
Revises: 3606d4a47663
Create Date: 2015-06-24 22:06:54.077035

"""

# revision identifiers, used by Alembic.
revision = '1c8be8d9bec3'
down_revision = '3606d4a47663'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_read_compose_feeds_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_read_compose_feeds_at')
    ### end Alembic commands ###
