"""Rename table UserTopicStatistics

Revision ID: 534c31b8ae8c
Revises: 381acdce0a35
Create Date: 2015-06-13 17:21:01.292205

"""

# revision identifiers, used by Alembic.
revision = '534c31b8ae8c'
down_revision = '381acdce0a35'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_topic_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answers_count', sa.Integer(), nullable=True),
    sa.Column('upvotes_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('show_order', sa.Integer(), nullable=True),
    sa.Column('experience', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_topic_statistics')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_topic_statistics',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('upvotes_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('answers_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('topic_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('selected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('show_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('experience', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], [u'topic.id'], name=u'user_topic_statistics_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'user_topic_statistics_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('user_topic_statistic')
    ### end Alembic commands ###
