"""Update user.

Revision ID: 244549f21df2
Revises: 50561236f3a0
Create Date: 2015-05-27 21:43:08.031884

"""

# revision identifiers, used by Alembic.
revision = '244549f21df2'
down_revision = '50561236f3a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('organization', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('position', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'position')
    op.drop_column('user', 'organization')
    op.drop_column('user', 'city')
    ### end Alembic commands ###
