"""Update Answer model.

Revision ID: 30bc9e463992
Revises: 1b2abe53ad3a
Create Date: 2015-06-10 17:22:38.222536

"""

# revision identifiers, used by Alembic.
revision = '30bc9e463992'
down_revision = '1b2abe53ad3a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'content_length')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('content_length', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
