"""Add locked to Topic

Revision ID: 50561236f3a0
Revises: 3c77900d8141
Create Date: 2015-05-27 19:10:50.721692

"""

# revision identifiers, used by Alembic.
revision = '50561236f3a0'
down_revision = '3c77900d8141'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('locked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'locked')
    ### end Alembic commands ###
