"""Add lock fields to Topic model.

Revision ID: 56a59330879f
Revises: 4876cee49bef
Create Date: 2015-06-01 08:15:19.676453

"""

# revision identifiers, used by Alembic.
revision = '56a59330879f'
down_revision = '4876cee49bef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('avatar_locked', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('child_topics_locked', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('desc_locked', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('name_locked', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('parent_topics_locked', sa.Boolean(), nullable=True))
    op.add_column('topic', sa.Column('wiki_locked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'wiki_locked')
    op.drop_column('topic', 'parent_topics_locked')
    op.drop_column('topic', 'name_locked')
    op.drop_column('topic', 'desc_locked')
    op.drop_column('topic', 'child_topics_locked')
    op.drop_column('topic', 'avatar_locked')
    ### end Alembic commands ###
