"""Update User model.

Revision ID: 5a66f56497fc
Revises: 1a0298aecde9
Create Date: 2015-06-22 09:07:43.735263

"""

# revision identifiers, used by Alembic.
revision = '5a66f56497fc'
down_revision = '1a0298aecde9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name_modify_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name_modify_count')
    ### end Alembic commands ###
