"""Add root to Topic

Revision ID: 27651591b3f5
Revises: 56a59330879f
Create Date: 2015-06-01 11:23:08.141700

"""

# revision identifiers, used by Alembic.
revision = '27651591b3f5'
down_revision = '56a59330879f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('root', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'root')
    ### end Alembic commands ###
