"""Add guide steps to User model.

Revision ID: 4ab8a4f268cf
Revises: 11e900fb08c3
Create Date: 2015-07-09 17:25:58.589820

"""

# revision identifiers, used by Alembic.
revision = '4ab8a4f268cf'
down_revision = '11e900fb08c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_guide_step', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('has_finish_guide_steps', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_finish_guide_steps')
    op.drop_column('user', 'current_guide_step')
    ### end Alembic commands ###
