"""Update Answer model.

Revision ID: 433420363893
Revises: 1d61f5c015c
Create Date: 2015-06-10 10:26:26.912059

"""

# revision identifiers, used by Alembic.
revision = '433420363893'
down_revision = '1d61f5c015c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('content_preview_length', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'content_preview_length')
    ### end Alembic commands ###
