"""Add last_read_notifications_at to User.

Revision ID: 3f2c86e3bf8b
Revises: 1c8be8d9bec3
Create Date: 2015-06-24 22:55:16.597582

"""

# revision identifiers, used by Alembic.
revision = '3f2c86e3bf8b'
down_revision = '1c8be8d9bec3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_read_notifications_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_read_notifications_at')
    ### end Alembic commands ###
