"""Add background to User model.

Revision ID: 3e4cd5c1f8bf
Revises: 487efd744e8d
Create Date: 2015-06-12 12:22:59.544318

"""

# revision identifiers, used by Alembic.
revision = '3e4cd5c1f8bf'
down_revision = '487efd744e8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('background', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'background')
    ### end Alembic commands ###
