"""Add LikeAnswerComment.

Revision ID: 3e1dd0faf4b9
Revises: 4be4542b23e9
Create Date: 2015-05-31 20:55:20.244428

"""

# revision identifiers, used by Alembic.
revision = '3e1dd0faf4b9'
down_revision = '4be4542b23e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_answer_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_answer_comment')
    ### end Alembic commands ###
