"""Add parent to AnswerComment model.

Revision ID: 3f052d6318f9
Revises: 3d98cd8a86fa
Create Date: 2015-06-02 14:14:20.429793

"""

# revision identifiers, used by Alembic.
revision = '3f052d6318f9'
down_revision = '3d98cd8a86fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer_comment', 'answer_comment', ['parent_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer_comment', type_='foreignkey')
    op.drop_column('answer_comment', 'parent_id')
    ### end Alembic commands ###
