"""Rename table UserTopicStatistics

Revision ID: 534c31b8ae8c
Revises: 381acdce0a35
Create Date: 2015-06-13 17:21:01.292205

"""

# revision identifiers, used by Alembic.
revision = '534c31b8ae8c'
down_revision = '381acdce0a35'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user_topic_statistics', 'user_topic_statistic')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
        op.rename_table('user_topic_statistic', 'user_topic_statistics')
    ### end Alembic commands ###
